name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"
      - name: Build package
        run: poetry build

      - name: Publish to GitHub Packages
        env:
          # Környezeti változók használata a konfiguráció helyett
          POETRY_REPOSITORIES_GITHUB_URL: https://pypi.pkg.github.com/${{ github.repository_owner }}
          POETRY_HTTP_BASIC_GITHUB_USERNAME: ${{ github.actor }}
          POETRY_HTTP_BASIC_GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: poetry publish --repository github -v
